# Pre-commit hooks 配置
# 在提交前自動執行程式碼檢查

repos:
  # Python 程式碼格式化
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        args: ['--line-length=100']
        files: ^query-service/.*\.py$

  # Import 排序
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=100']
        files: ^query-service/.*\.py$

  # 程式碼檢查
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--extend-ignore=E203,W503']
        files: ^query-service/.*\.py$

  # 類型檢查
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-boto3]
        args: ['--ignore-missing-imports', '--disable-error-code=misc']
        files: ^query-service/.*\.py$

  # 安全性檢查
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        args: ['-ll']
        files: ^query-service/.*\.py$

  # YAML 檢查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  # Markdown 檢查
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: [--disable, MD013, MD033, MD040, MD031, MD024, MD029, MD036, MD034]

  # Dockerfile 檢查 - 使用穩定版本
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3013, --ignore, DL3015, --ignore, DL3045]

  # 祕密檢測
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
